/*Answers to multiple choice and fill-in-the-blank questions*/
var add = tests.add;

/*
 * template:
 * add(question, answer0 [, answer1, ...]);
 */

// CCNA3 Scaling Networks v6.0 Chapter 9
add('What are two reasons for creating an OSPF network with multiple areas? (Choose two.)',
    'to reduce SPF calculations',
    'to reduce use of memory and processor resources');
add('What is used to facilitate hierarchical routing in OSPF?',
    'the use of multiple areas');
add('Which two statements correctly describe OSPF type 3 LSAs? (Choose two.)',
    'Type 3 LSAs are generated without requiring a full SPF calculation.',
    'Type 3 LSAs are used to update routes between OSPF areas.');
add('Which characteristic describes both ABRs and ASBRs that are implemented in a multiarea OSPF network?',
    'They are required to perform any summarization or redistribution tasks.');
add('What type of OSPF LSA is originated by ASBR routers to advertise external routes?',
    'type 5');
add('What OSPF LSA type is used to inform routers of the router ID of the DR in each multiaccess network in an OSPF area?',
    'type 2');
add('Which two statements are correct? (Choose two.)',
    'The routing table contains routes from multiple areas.',
    'To reach network 192.168.1.0, traffic will exit via the Serial0/0/0 interface.');
add('What routing table descriptor is used to identify OSPF summary networks that originate from an ABR?',
    'IA');
add('A network administrator is verifying a multi-area OSPF configuration by checking the routing table on a router in area 1. The administrator notices a route to a network that is connected to a router in area 2. Which code appears in front of this route in the routing table within area 1?',
    'IA');
add('What can be concluded about network 192.168.4.0 in the R2 routing table?',
    'The network was learned from a router within the same area as R2.');
add('Which three steps in the design and implementation of a multiarea OSPF network are considered planning steps? (Choose three.)',
    'Define the OSPF parameters.',
    'Gather the required parameters.',
    'Define the network requirements.');
add('Which two networks are part of the summary route 192.168.32.0/22? (Choose two.)',
    '192.168.33.0/24',
    '192.168.35.0/24');
add('What is indicated by the O IA in the router output?',
    'The route was learned from another area.');
add('A network administrator has been asked to summarize the networks shown in the exhibit as part of a multiarea OSPF implementation. All addresses are using a subnet mask of 255.255.255.0. What is the correct summarization for these eight networks?',
    '10.0.0.0 255.255.240.0');
add('The network administrator has been asked to summarize the routes for a new OSPF area. The networks to be summarized are 172.16.8.0, 172.16.10.0, and 172.16.12.0 with subnet masks of 255.255.255.0 for each network. Which command should the administrator use to forward the summary route for area 15 into area 0?',
    'area 15 range 172.16.8.0 255.255.248.0');
add('OSPF type 2 LSA messages are only generated by the router to advertise routes in multiaccess networks.',
    'designated');
add('An ASBR generates type LSAs for each of its external routes and floods them into the area that it is connected to.',
    '5');
add('A type LSA identifies the ASBR and provides a route to it.',
    '4');
add('The command must be issued to configure R1 for multiarea OSPF.',
    'network 192.168.10.128 0.0.0.127 area 1');
add('Why are users in the OSPF network not able to access the Internet?',
    'The network statement is misconfigured on router R1.');
add('What is the missing command on router R2 to establish an adjacency between routers R1 and R3?',
    'network 172.16.10.0 0.0.0.255 area 0');
add('What information is contained within an OSPF type 4 LSA?',
    'the route to an ASBR');
add('Which type of OSPF router has interfaces connected to multiple OSPF areas?',
    'ABR');
add('What is preventing users who are connected to router R2 from accessing resources located either within the network 192.168.1.0 or the internet?',
    'The router R2 is not receiving any updates from either router R1 or R3.');
add('Which type of OSPF router will generate type 3 LSAs?',
    'ABR');
add('Which type of OSPF LSA is generated by an ASBR and includes external routes?',
    'type 5');
add('What is the role of router R2 in the OSPF domain?',
    'ABR');



/*Prompts for matching questions and Packet Tracer Labs*/
add = prompts.add;

/*
 * template:
 * add('helper label');
 */

add('internal > same, Area > multiple, backbone > backbone, Autonomous > non-OSPF');
